##### Data Cleaning Age Specific Fertility Rate (age 25-29) #####

In [1]:
# import Pandas

import pandas as pd

Note: When the csv file was created:
- Deleted unneccesary 5 rows above headers which were not impacting data.
- Changed header names adding 'year_' before year\
    example: 2019 -> year_2019
- Added column name 'region_code' where empty header was.

In [2]:
# import nomis_ASFR_25_29.csv into Panda

data = pd.read_csv('../data/raw/modified_headers/fertility_rate/nomis_ASFR_25_29.csv')
df = pd.DataFrame(data)
display(df)

,Area,region_code,year_2019,year_2020,year_2021,year_2022,year_2023,year_2024
0,gor:North East,E12000001,92.0,89.0,90.8,86.9,84.2,81.9
1,gor:North West,E12000002,93.8,89.8,90.1,86.6,81.3,80.4
2,gor:Yorkshire and The Humber,E12000003,97.9,92.1,93.3,88.8,85.3,84.4
3,gor:East Midlands,E12000004,96.2,91.9,92.7,90.0,85.7,85.1
4,gor:West Midlands,E12000005,100.4,99.0,97.2,95.8,92.9,94.5
...,...,...,...,...,...,...,...,...
526,combauth:Hull and East Yorkshire,E47000016,99.0,95.5,95.7,94.7,92.0,87.1
527,combauth:Greater Lincolnshire,E47000017,99.1,97.2,96.7,96.4,89.0,88.2
528,combauth:Lancashire,E47000018,103.6,101.2,103.4,98.1,93.1,95.2
529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,2021 rates are missing as they require mid-202...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Note: Before cleaning the data, dropped irrelevant data as we only need regional level

In [3]:
# Check the area name and region_code
df[['Area', 'region_code']].head(20)
region_level = df[(df['region_code'] == 'E12000001') 
                | (df['region_code'] == 'E12000002') 
                | (df['region_code'] == 'E12000003') 
                | (df['region_code'] == 'E12000004') 
                | (df['region_code'] == 'E12000005') 
                | (df['region_code'] == 'E12000006') 
                | (df['region_code'] == 'E12000007') 
                | (df['region_code'] == 'E12000008') 
                | (df['region_code'] == 'E12000009') 
                | (df['region_code'] == 'W92000004') 
                ]
display(region_level)

print('*Note: There are two Wales rows with the same data as it appears one in region level and one in country level')

,Area,region_code,year_2019,year_2020,year_2021,year_2022,year_2023,year_2024
0,gor:North East,E12000001,92.0,89.0,90.8,86.9,84.2,81.9
1,gor:North West,E12000002,93.8,89.8,90.1,86.6,81.3,80.4
2,gor:Yorkshire and The Humber,E12000003,97.9,92.1,93.3,88.8,85.3,84.4
3,gor:East Midlands,E12000004,96.2,91.9,92.7,90.0,85.7,85.1
4,gor:West Midlands,E12000005,100.4,99.0,97.2,95.8,92.9,94.5
5,gor:East,E12000006,93.2,88.0,90.1,86.5,83.0,80.9
6,gor:London,E12000007,58.8,56.2,55.2,53.9,50.9,51.3
7,gor:South East,E12000008,85.1,82.1,82.7,79.6,75.0,73.0
8,gor:South West,E12000009,86.5,82.2,82.8,75.8,73.1,68.6
9,gor:Wales,W92000004,91.5,87.5,89.4,86.2,80.7,76.9
513,country:Wales,W92000004,91.5,87.5,89.4,86.2,80.7,76.9

*Note: There are two Wales rows with the same data as it appears one in region level and one in country level

Create the regional level only DataFrame

In [4]:
# Copy the origianl the table to make regional level only table (10 regions)
df_copy = df.copy()

In [5]:
# Delete all the rows except where the Area name starts with 'gor:'
df_by_region = df_copy[df_copy['Area'].str.startswith('gor:')].copy()
display(df_by_region)

,Area,region_code,year_2019,year_2020,year_2021,year_2022,year_2023,year_2024
0,gor:North East,E12000001,92.0,89.0,90.8,86.9,84.2,81.9
1,gor:North West,E12000002,93.8,89.8,90.1,86.6,81.3,80.4
2,gor:Yorkshire and The Humber,E12000003,97.9,92.1,93.3,88.8,85.3,84.4
3,gor:East Midlands,E12000004,96.2,91.9,92.7,90.0,85.7,85.1
4,gor:West Midlands,E12000005,100.4,99.0,97.2,95.8,92.9,94.5
5,gor:East,E12000006,93.2,88.0,90.1,86.5,83.0,80.9
6,gor:London,E12000007,58.8,56.2,55.2,53.9,50.9,51.3
7,gor:South East,E12000008,85.1,82.1,82.7,79.6,75.0,73.0
8,gor:South West,E12000009,86.5,82.2,82.8,75.8,73.1,68.6
9,gor:Wales,W92000004,91.5,87.5,89.4,86.2,80.7,76.9

In [6]:
# Detailed information about the region DataFrame
print(f'Detailed information:\n{df_by_region.info()}')

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Area         10 non-null     str
 1   region_code  10 non-null     str
 2   year_2019    10 non-null     float64
 3   year_2020    10 non-null     float64
 4   year_2021    10 non-null     float64
 5   year_2022    10 non-null     float64
 6   year_2023    10 non-null     float64
 7   year_2024    10 non-null     float64
dtypes: float64(6), str(2)
memory usage: 772.0 bytes
Detailed information:
None

In [7]:
# Statistical summary
print('Statistical summary:')
print(f'\nyear_2019:\n{df_by_region['year_2019'].describe()}')
print(f'\nyear_2020:\n{df_by_region['year_2020'].describe()}')
print(f'\nyear_2021:\n{df_by_region['year_2021'].describe()}')
print(f'\nyear_2022:\n{df_by_region['year_2022'].describe()}')
print(f'\nyear_2023:\n{df_by_region['year_2023'].describe()}')
print(f'\nyear_2024:\n{df_by_region['year_2024'].describe()}')

Statistical summary:

year_2019:
count     10.000000
mean      89.540000
std       11.773435
min       58.800000
25%       87.750000
50%       92.600000
75%       95.600000
max      100.400000
Name: year_2019, dtype: float64

year_2020:
count    10.000000
mean     85.780000
std      11.488719
min      56.200000
25%      83.525000
50%      88.500000
75%      91.375000
max      99.000000
Name: year_2020, dtype: float64

year_2021:
count    10.000000
mean     86.430000
std      11.831037
min      55.200000
25%      84.450000
50%      90.100000
75%      92.225000
max      97.200000
Name: year_2021, dtype: float64

year_2022:
count    10.000000
mean     83.010000
std      11.582309
min      53.900000
25%      81.250000
50%      86.550000
75%      88.325000
max      95.800000
Name: year_2022, dtype: float64

year_2023:
count    10.000000
mean     79.210000
std      11.396827
min      50.900000
25%      76.425000
50%      82.150000
75%      85.025000
max      92.900000
Name: year_2023, dtype: float64

year_2024:
count    10.000000
mean     77.700000
std      11.640733
min      51.300000
25%      73.975000
50%      80.650000
75%      83.775000
max      94.500000
Name: year_2024, dtype: float64

In [9]:
# Find missing values
print('Value Missing:')
print(df_by_region.isnull().sum())
print(f'\nTotal missing values: {df_by_region.isnull().sum().sum()}')

Value Missing:
Area           0
region_code    0
year_2019      0
year_2020      0
year_2021      0
year_2022      0
year_2023      0
year_2024      0
dtype: int64

Total missing values: 0

In [10]:
# Check duplicate records
print('Duplicate Records:')
print(f'Number of duplicate rows: {df_by_region.duplicated().sum()}')

Duplicate Records:
Number of duplicate rows: 0

In [11]:
# Find inconsistent formats
print('Inconsistetnt Formats:')
print('Area column issue')
areas = [area for area in df_by_region['Area'] if str(area).startswith(' ') or str(area).endswith(' ')]   # used str() to avoid attribute errors on NaN rows
print(f'- Whitespace issue: {len(areas)}') 
print(f'- Empty strings: {df_by_region[df_by_region['Area'] == ''].shape[0]}')

print('\nregion_code column issue:')
codes = [code for code in df_by_region['region_code'] if str(code).startswith(' ') or str(code).endswith(' ')]   # used str() to avoid attribute errors on NaN rows
print(f'- Whitespace issue in region_code column: {len(codes)}') 
print(f'- Empty strings: {df_by_region[df_by_region['region_code'] == ''].shape[0]}')

Inconsistetnt Formats:
Area column issue
- Whitespace issue: 0
- Empty strings: 0

region_code column issue:
- Whitespace issue in region_code column: 0
- Empty strings: 0

In [12]:
# remove 'gor:' in Area colummn to be align with income and house_price dataset

df_by_region['Area'] = df_by_region['Area'].str.replace('gor:', '')
display(df_by_region)

,Area,region_code,year_2019,year_2020,year_2021,year_2022,year_2023,year_2024
0,North East,E12000001,92.0,89.0,90.8,86.9,84.2,81.9
1,North West,E12000002,93.8,89.8,90.1,86.6,81.3,80.4
2,Yorkshire and The Humber,E12000003,97.9,92.1,93.3,88.8,85.3,84.4
3,East Midlands,E12000004,96.2,91.9,92.7,90.0,85.7,85.1
4,West Midlands,E12000005,100.4,99.0,97.2,95.8,92.9,94.5
5,East,E12000006,93.2,88.0,90.1,86.5,83.0,80.9
6,London,E12000007,58.8,56.2,55.2,53.9,50.9,51.3
7,South East,E12000008,85.1,82.1,82.7,79.6,75.0,73.0
8,South West,E12000009,86.5,82.2,82.8,75.8,73.1,68.6
9,Wales,W92000004,91.5,87.5,89.4,86.2,80.7,76.9

In [13]:
# Change to align with income and house_price dataset column names
# Change 'Area' to 'regional_name' and region_code to regional_code

df_by_region.rename(columns={'Area': 'region_name'}, inplace=True)

display(df_by_region)

,region_name,region_code,year_2019,year_2020,year_2021,year_2022,year_2023,year_2024
0,North East,E12000001,92.0,89.0,90.8,86.9,84.2,81.9
1,North West,E12000002,93.8,89.8,90.1,86.6,81.3,80.4
2,Yorkshire and The Humber,E12000003,97.9,92.1,93.3,88.8,85.3,84.4
3,East Midlands,E12000004,96.2,91.9,92.7,90.0,85.7,85.1
4,West Midlands,E12000005,100.4,99.0,97.2,95.8,92.9,94.5
5,East,E12000006,93.2,88.0,90.1,86.5,83.0,80.9
6,London,E12000007,58.8,56.2,55.2,53.9,50.9,51.3
7,South East,E12000008,85.1,82.1,82.7,79.6,75.0,73.0
8,South West,E12000009,86.5,82.2,82.8,75.8,73.1,68.6
9,Wales,W92000004,91.5,87.5,89.4,86.2,80.7,76.9

In [25]:
# export the df_by_region df to csv file excluding index
df_by_region.to_csv('../data/cleaned/age22_29_ASFR_by_regional.csv', index=False)