In [1]:
# Import Pandas
import pandas as pd

In [2]:
# Imported warning modules to ignore performance warning as data is not big enough to consider efficiency of performance 
import warnings
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

Import cleaned dataset for data integration\
Imported data:
- Data 1: age25_29_ASFR_by_regional.csv
- Data 2: age22_29_five_year_yearly_gross_income_regional.csv
- Data 3: yearly_house_price_2020_2026Q1_regional.csv
- Data 4: affordability_2020_2024_regional.csv

In [3]:
# Import fertility rate data (for age 25-29)
df_asfr = pd.read_csv('../data/cleaned/age25_29_ASFR_by_regional.csv')
display(df_asfr)

,region_name,region_code,year_2019,year_2020,year_2021,year_2022,year_2023,year_2024
0,North East,E12000001,92.0,89.0,90.8,86.9,84.2,81.9
1,North West,E12000002,93.8,89.8,90.1,86.6,81.3,80.4
2,Yorkshire and The Humber,E12000003,97.9,92.1,93.3,88.8,85.3,84.4
3,East Midlands,E12000004,96.2,91.9,92.7,90.0,85.7,85.1
4,West Midlands,E12000005,100.4,99.0,97.2,95.8,92.9,94.5
5,East,E12000006,93.2,88.0,90.1,86.5,83.0,80.9
6,London,E12000007,58.8,56.2,55.2,53.9,50.9,51.3
7,South East,E12000008,85.1,82.1,82.7,79.6,75.0,73.0
8,South West,E12000009,86.5,82.2,82.8,75.8,73.1,68.6
9,Wales,W92000004,91.5,87.5,89.4,86.2,80.7,76.9

In [4]:
# Import gross income data (for age 22-29)
df_gross_income_original = pd.read_csv('../data/cleaned/age22_29_five_year_yearly_gross_income_regional.csv')
display(df_gross_income_original)

,region_code,region_name,2020_median_yearly_gross,2021_median_yearly_gross,2022_median_yearly_gross,2023_median_yearly_gross,2024_median_yearly_gross
0,E12000001,North East,20930.0,22016.8,24044.8,25911.6,26764.4
1,E12000002,North West,22349.6,22724.0,24653.2,26910.0,29250.0
2,E12000003,Yorkshire and The Humber,21533.2,23145.2,24715.6,26026.0,27705.6
3,E12000004,East Midlands,21923.2,23337.6,24731.2,26176.8,28308.8
4,E12000005,West Midlands,22126.0,23665.2,24850.8,26884.0,28579.2
5,E12000006,East,22859.2,24195.6,25911.6,28095.6,28901.6
6,E12000007,London,29562.0,30492.8,31933.2,33898.8,35599.2
7,E12000008,South East,23566.4,24913.2,26182.0,28901.6,29894.8
8,E12000009,South West,21678.8,22531.6,24913.2,26286.0,28454.4
9,W92000004,Wales,21070.4,21912.8,24388.0,25771.2,27414.4
10,S92000003,Scotland,22796.8,23920.0,25656.8,28459.6,29260.4

In [5]:
# Import house price
df_house_price_original = pd.read_csv('../data/cleaned/yearly_house_price_2020_2026Q1_regional.csv')
display(df_house_price_original)

   region_code region_name  year  house_price
0    E12000001  North East  2020     180000.0
1    E12000001  North East  2021     192000.0
2    E12000001  North East  2022     197500.0
3    E12000001  North East  2023     200250.0
4    E12000001  North East  2024     205000.0
..         ...         ...   ...          ...
72   S92000003    Scotland  2022     230250.0
73   S92000003    Scotland  2023     229750.0
74   S92000003    Scotland  2024     232000.0
75   S92000003    Scotland  2025     239750.0
76   S92000003    Scotland  2026     240000.0

[77 rows x 4 columns]

In [6]:
# Import affordability
df_affordability = pd.read_csv('../data/cleaned/affordability_2020_2024_regional.csv')
display(df_affordability)

  region_code               region_name   2020   2021   2022   2023   2024
0   W92000004                     Wales   5.85   6.49   6.39   6.13   6.02
1   E12000001                North East   5.20   5.78   5.20   5.28   5.02
2   E12000002                North West   5.89   6.73   6.48   6.34   6.09
3   E12000003  Yorkshire and The Humber   5.90   6.56   6.22   6.39   5.96
4   E12000004             East Midlands   6.80   7.82   7.66   7.60   7.03
5   E12000005             West Midlands   6.88   7.75   7.42   7.35   7.00
6   E12000006                      East   8.94  10.14   9.73   9.58   8.70
7   E12000007                    London  12.59  13.58  13.17  12.50  11.83
8   E12000008                South East   9.65  10.75  10.49  10.28   9.42
9   E12000009                South West   8.62   9.82   9.43   9.23   8.50

Data cleaning to be done prior to the integration:

Gross Income Data
- Delete 'Scotland' region data as Scotland is out of the scope of our project

In [7]:
# Delete Scotland rows in gross income data in the copied dataframe df_gross_income
df_gross_income = df_gross_income_original[(df_gross_income_original['region_name'] != 'Scotland')].copy()

display(df_gross_income)

,region_code,region_name,2020_median_yearly_gross,2021_median_yearly_gross,2022_median_yearly_gross,2023_median_yearly_gross,2024_median_yearly_gross
0,E12000001,North East,20930.0,22016.8,24044.8,25911.6,26764.4
1,E12000002,North West,22349.6,22724.0,24653.2,26910.0,29250.0
2,E12000003,Yorkshire and The Humber,21533.2,23145.2,24715.6,26026.0,27705.6
3,E12000004,East Midlands,21923.2,23337.6,24731.2,26176.8,28308.8
4,E12000005,West Midlands,22126.0,23665.2,24850.8,26884.0,28579.2
5,E12000006,East,22859.2,24195.6,25911.6,28095.6,28901.6
6,E12000007,London,29562.0,30492.8,31933.2,33898.8,35599.2
7,E12000008,South East,23566.4,24913.2,26182.0,28901.6,29894.8
8,E12000009,South West,21678.8,22531.6,24913.2,26286.0,28454.4
9,W92000004,Wales,21070.4,21912.8,24388.0,25771.2,27414.4

In [8]:
# Create df_all to integrate 3 dataframe
region_code_list = df_gross_income['region_code'].tolist()
region_name_list = df_gross_income['region_name'].tolist()
year_list = [2020, 2021, 2022, 2023, 2024]

# print(region_code_list)
# print(region_name_list)
# print(len(region_code_list))

# create a new empty dataframe with columns
df_all = pd.DataFrame(columns=['region_code', 'region_name', 'year'])
# add row for every 'region_code', 'region_name', 'year'
for i in range(len(region_code_list)):
    for y in year_list:
        new_row = {'region_code': region_code_list[i], 'region_name': region_name_list[i], 'year': y}
        df_all.loc[len(df_all)] = new_row

display(df_all)

   region_code               region_name  year
0    E12000001                North East  2020
1    E12000001                North East  2021
2    E12000001                North East  2022
3    E12000001                North East  2023
4    E12000001                North East  2024
5    E12000002                North West  2020
6    E12000002                North West  2021
7    E12000002                North West  2022
8    E12000002                North West  2023
9    E12000002                North West  2024
10   E12000003  Yorkshire and The Humber  2020
11   E12000003  Yorkshire and The Humber  2021
12   E12000003  Yorkshire and The Humber  2022
13   E12000003  Yorkshire and The Humber  2023
14   E12000003  Yorkshire and The Humber  2024
15   E12000004             East Midlands  2020
16   E12000004             East Midlands  2021
17   E12000004             East Midlands  2022
18   E12000004             East Midlands  2023
19   E12000004             East Midlands  2024
20   E12000005             West Midlands  2020
21   E12000005             West Midlands  2021
22   E12000005             West Midlands  2022
23   E12000005             West Midlands  2023
24   E12000005             West Midlands  2024
25   E12000006                      East  2020
26   E12000006                      East  2021
27   E12000006                      East  2022
28   E12000006                      East  2023
29   E12000006                      East  2024
30   E12000007                    London  2020
31   E12000007                    London  2021
32   E12000007                    London  2022
33   E12000007                    London  2023
34   E12000007                    London  2024
35   E12000008                South East  2020
36   E12000008                South East  2021
37   E12000008                South East  2022
38   E12000008                South East  2023
39   E12000008                South East  2024
40   E12000009                South West  2020
41   E12000009                South West  2021
42   E12000009                South West  2022
43   E12000009                South West  2023
44   E12000009                South West  2024
45   W92000004                     Wales  2020
46   W92000004                     Wales  2021
47   W92000004                     Wales  2022
48   W92000004                     Wales  2023
49   W92000004                     Wales  2024

In [9]:
# To make sure the data being added to df_all mapping to the rows in the set of 'region_code, 'region_name' 'year' columns,
# make the rows in those colums as row index
df_all.set_index(['region_code', 'region_name', 'year'], inplace = True)
display(df_all)

Empty DataFrame
Columns: []
Index: [(E12000001, North East, 2020), (E12000001, North East, 2021), (E12000001, North East, 2022), (E12000001, North East, 2023), (E12000001, North East, 2024), (E12000002, North West, 2020), (E12000002, North West, 2021), (E12000002, North West, 2022), (E12000002, North West, 2023), (E12000002, North West, 2024), (E12000003, Yorkshire and The Humber, 2020), (E12000003, Yorkshire and The Humber, 2021), (E12000003, Yorkshire and The Humber, 2022), (E12000003, Yorkshire and The Humber, 2023), (E12000003, Yorkshire and The Humber, 2024), (E12000004, East Midlands, 2020), (E12000004, East Midlands, 2021), (E12000004, East Midlands, 2022), (E12000004, East Midlands, 2023), (E12000004, East Midlands, 2024), (E12000005, West Midlands, 2020), (E12000005, West Midlands, 2021), (E12000005, West Midlands, 2022), (E12000005, West Midlands, 2023), (E12000005, West Midlands, 2024), (E12000006, East, 2020), (E12000006, East, 2021), (E12000006, East, 2022), (E12000006, East, 2023), (E12000006, East, 2024), (E12000007, London, 2020), (E12000007, London, 2021), (E12000007, London, 2022), (E12000007, London, 2023), (E12000007, London, 2024), (E12000008, South East, 2020), (E12000008, South East, 2021), (E12000008, South East, 2022), (E12000008, South East, 2023), (E12000008, South East, 2024), (E12000009, South West, 2020), (E12000009, South West, 2021), (E12000009, South West, 2022), (E12000009, South West, 2023), (E12000009, South West, 2024), (W92000004, Wales, 2020), (W92000004, Wales, 2021), (W92000004, Wales, 2022), (W92000004, Wales, 2023), (W92000004, Wales, 2024)]

In [10]:
# test if this syntax works as expected.
# df_all.loc[('E12000001', 'North East', 2022), 'median_yearly_gross'] = 123.4
# display(df_all)
# DF displayed as expected.

Add new column of fertility rate data in df_all dataframe

In [11]:
# Create a list of dictionaries for fertility rate data in each row
# To create list of dictionaries, use to_dict(orient='records')
for row_fertility_dict in df_asfr.to_dict(orient='records'):
    # print(row_income_dict)
    
    # for each row in the df_asfr table
    region_code = row_fertility_dict['region_code']
    region_name = row_fertility_dict['region_name']

    for year in year_list:

        # for each year, get the row_fertility_dict value from the row dictionary
        asfr = row_fertility_dict[f'year_{year}']
        # print(gross_income)

        # push this gross_income value, into the df_all table
        df_all.loc[(region_code, region_name, year), 'fertility_rate'] = asfr

In [12]:
# Check
display(df_all)

                                           fertility_rate
region_code region_name              year
E12000001   North East               2020            89.0
                                     2021            90.8
                                     2022            86.9
                                     2023            84.2
                                     2024            81.9
E12000002   North West               2020            89.8
                                     2021            90.1
                                     2022            86.6
                                     2023            81.3
                                     2024            80.4
E12000003   Yorkshire and The Humber 2020            92.1
                                     2021            93.3
                                     2022            88.8
                                     2023            85.3
                                     2024            84.4
E12000004   East Midlands            2020            91.9
                                     2021            92.7
                                     2022            90.0
                                     2023            85.7
                                     2024            85.1
E12000005   West Midlands            2020            99.0
                                     2021            97.2
                                     2022            95.8
                                     2023            92.9
                                     2024            94.5
E12000006   East                     2020            88.0
                                     2021            90.1
                                     2022            86.5
                                     2023            83.0
                                     2024            80.9
E12000007   London                   2020            56.2
                                     2021            55.2
                                     2022            53.9
                                     2023            50.9
                                     2024            51.3
E12000008   South East               2020            82.1
                                     2021            82.7
                                     2022            79.6
                                     2023            75.0
                                     2024            73.0
E12000009   South West               2020            82.2
                                     2021            82.8
                                     2022            75.8
                                     2023            73.1
                                     2024            68.6
W92000004   Wales                    2020            87.5
                                     2021            89.4
                                     2022            86.2
                                     2023            80.7
                                     2024            76.9

Add new column of gross income data in df_all dataframe

In [13]:
# Create a list of dictionaries for income data in each row
# To create list of dictionaries, use to_dict(orient='records')
for row_income_dict in df_gross_income.to_dict(orient='records'):
    # print(row_income_dict)
    
    # for each row in the df_gross_income table
    region_code = row_income_dict['region_code']
    region_name = row_income_dict['region_name']

    for year in year_list:

        # for each year, get the row_income_dict value from the row dictionary
        gross_income = row_income_dict[f'{year}_median_yearly_gross']
        # print(gross_income)

        # push this gross_income value, into the df_all table
        df_all.loc[(region_code, region_name, year), "median_yearly_gross"] = gross_income

In [14]:
# Check
display(df_all)

                                           fertility_rate  median_yearly_gross
region_code region_name              year
E12000001   North East               2020            89.0              20930.0
                                     2021            90.8              22016.8
                                     2022            86.9              24044.8
                                     2023            84.2              25911.6
                                     2024            81.9              26764.4
E12000002   North West               2020            89.8              22349.6
                                     2021            90.1              22724.0
                                     2022            86.6              24653.2
                                     2023            81.3              26910.0
                                     2024            80.4              29250.0
E12000003   Yorkshire and The Humber 2020            92.1              21533.2
                                     2021            93.3              23145.2
                                     2022            88.8              24715.6
                                     2023            85.3              26026.0
                                     2024            84.4              27705.6
E12000004   East Midlands            2020            91.9              21923.2
                                     2021            92.7              23337.6
                                     2022            90.0              24731.2
                                     2023            85.7              26176.8
                                     2024            85.1              28308.8
E12000005   West Midlands            2020            99.0              22126.0
                                     2021            97.2              23665.2
                                     2022            95.8              24850.8
                                     2023            92.9              26884.0
                                     2024            94.5              28579.2
E12000006   East                     2020            88.0              22859.2
                                     2021            90.1              24195.6
                                     2022            86.5              25911.6
                                     2023            83.0              28095.6
                                     2024            80.9              28901.6
E12000007   London                   2020            56.2              29562.0
                                     2021            55.2              30492.8
                                     2022            53.9              31933.2
                                     2023            50.9              33898.8
                                     2024            51.3              35599.2
E12000008   South East               2020            82.1              23566.4
                                     2021            82.7              24913.2
                                     2022            79.6              26182.0
                                     2023            75.0              28901.6
                                     2024            73.0              29894.8
E12000009   South West               2020            82.2              21678.8
                                     2021            82.8              22531.6
                                     2022            75.8              24913.2
                                     2023            73.1              26286.0
                                     2024            68.6              28454.4
W92000004   Wales                    2020            87.5              21070.4
                                     2021            89.4              21912.8
                                     2022            86.2              24388.0
                                     2023            80.7              25771.2
                                     2024            76.9              27414.4

Add new column of affordability data in df_all dataframe

In [15]:
# Create a list of dictionaries for affordability data in each row
# To create list of dictionaries, use to_dict(orient='records')
for row_affordability_dict in df_affordability.to_dict(orient='records'):
    # print(row_income_dict)
    
    # for each row in the df_gross_income table
    region_code = row_affordability_dict['region_code']
    region_name = row_affordability_dict['region_name']

    for year in year_list:

        # for each year, get the row_income_dict value from the row dictionary
        affordability = row_affordability_dict[f'{year}']
        # print(gross_income)

        # push this gross_income value, into the df_all table
        df_all.loc[(region_code, region_name, year), "median_affordability"] = affordability

In [16]:
# Check
display(df_all)

                                           fertility_rate  \
region_code region_name              year
E12000001   North East               2020            89.0
                                     2021            90.8
                                     2022            86.9
                                     2023            84.2
                                     2024            81.9
E12000002   North West               2020            89.8
                                     2021            90.1
                                     2022            86.6
                                     2023            81.3
                                     2024            80.4
E12000003   Yorkshire and The Humber 2020            92.1
                                     2021            93.3
                                     2022            88.8
                                     2023            85.3
                                     2024            84.4
E12000004   East Midlands            2020            91.9
                                     2021            92.7
                                     2022            90.0
                                     2023            85.7
                                     2024            85.1
E12000005   West Midlands            2020            99.0
                                     2021            97.2
                                     2022            95.8
                                     2023            92.9
                                     2024            94.5
E12000006   East                     2020            88.0
                                     2021            90.1
                                     2022            86.5
                                     2023            83.0
                                     2024            80.9
E12000007   London                   2020            56.2
                                     2021            55.2
                                     2022            53.9
                                     2023            50.9
                                     2024            51.3
E12000008   South East               2020            82.1
                                     2021            82.7
                                     2022            79.6
                                     2023            75.0
                                     2024            73.0
E12000009   South West               2020            82.2
                                     2021            82.8
                                     2022            75.8
                                     2023            73.1
                                     2024            68.6
W92000004   Wales                    2020            87.5
                                     2021            89.4
                                     2022            86.2
                                     2023            80.7
                                     2024            76.9

                                           median_yearly_gross  \
region_code region_name              year
E12000001   North East               2020              20930.0
                                     2021              22016.8
                                     2022              24044.8
                                     2023              25911.6
                                     2024              26764.4
E12000002   North West               2020              22349.6
                                     2021              22724.0
                                     2022              24653.2
                                     2023              26910.0
                                     2024              29250.0
E12000003   Yorkshire and The Humber 2020              21533.2
                                     2021              23145.2
                                     2022              24715.6
                                     2023              26026.0
                                     2024              27705.6
E12000004   East Midlands            2020              21923.2
                                     2021              23337.6
                                     2022              24731.2
                                     2023              26176.8
                                     2024              28308.8
E12000005   West Midlands            2020              22126.0
                                     2021              23665.2
                                     2022              24850.8
                                     2023              26884.0
                                     2024              28579.2
E12000006   East                     2020              22859.2
                                     2021              24195.6
                                     2022              25911.6
                                     2023              28095.6
                                     2024              28901.6
E12000007   London                   2020              29562.0
                                     2021              30492.8
                                     2022              31933.2
                                     2023              33898.8
                                     2024              35599.2
E12000008   South East               2020              23566.4
                                     2021              24913.2
                                     2022              26182.0
                                     2023              28901.6
                                     2024              29894.8
E12000009   South West               2020              21678.8
                                     2021              22531.6
                                     2022              24913.2
                                     2023              26286.0
                                     2024              28454.4
W92000004   Wales                    2020              21070.4
                                     2021              21912.8
                                     2022              24388.0
                                     2023              25771.2
                                     2024              27414.4

                                           median_affordability
region_code region_name              year
E12000001   North East               2020                  5.20
                                     2021                  5.78
                                     2022                  5.20
                                     2023                  5.28
                                     2024                  5.02
E12000002   North West               2020                  5.89
                                     2021                  6.73
                                     2022                  6.48
                                     2023                  6.34
                                     2024                  6.09
E12000003   Yorkshire and The Humber 2020                  5.90
                                     2021                  6.56
                                     2022                  6.22
                                     2023                  6.39
                                     2024                  5.96
E12000004   East Midlands            2020                  6.80
                                     2021                  7.82
                                     2022                  7.66
                                     2023                  7.60
                                     2024                  7.03
E12000005   West Midlands            2020                  6.88
                                     2021                  7.75
                                     2022                  7.42
                                     2023                  7.35
                                     2024                  7.00
E12000006   East                     2020                  8.94
                                     2021                 10.14
                                     2022                  9.73
                                     2023                  9.58
                                     2024                  8.70
E12000007   London                   2020                 12.59
                                     2021                 13.58
                                     2022                 13.17
                                     2023                 12.50
                                     2024                 11.83
E12000008   South East               2020                  9.65
                                     2021                 10.75
                                     2022                 10.49
                                     2023                 10.28
                                     2024                  9.42
E12000009   South West               2020                  8.62
                                     2021                  9.82
                                     2022                  9.43
                                     2023                  9.23
                                     2024                  8.50
W92000004   Wales                    2020                  5.85
                                     2021                  6.49
                                     2022                  6.39
                                     2023                  6.13
                                     2024                  6.02

In [17]:
print('Integrated table informaiton:\n')
print(f'\n{df_all.info()}')
print(f'\nMissing values: {df_all.isnull().sum().sum()}')
print(f'\nStatistic summary:\n{df_all.describe()}')

Integrated table informaiton:

<class 'pandas.DataFrame'>
MultiIndex: 50 entries, ('E12000001', 'North East', np.int64(2020)) to ('W92000004', 'Wales', np.int64(2024))
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fertility_rate        50 non-null     float64
 1   median_yearly_gross   50 non-null     float64
 2   median_affordability  50 non-null     float64
dtypes: float64(3)
memory usage: 3.7+ KB

None

Missing values: 0

Statistic summary:
       fertility_rate  median_yearly_gross  median_affordability
count       50.000000            50.000000               50.0000
mean        82.426000         25771.824000                8.0036
std         11.646648          3307.762708                2.2463
min         50.900000         20930.000000                5.0200
25%         80.475000         23193.300000                6.2500
50%         85.200000         25342.200000                7.3850
75%         89.950000         27998.100000                9.5425
max         99.000000         35599.200000               13.5800

In [18]:
# export df_all dataframe to csv file
df_all.to_csv('../data/master/master_dataset_with_affordability.csv')