In [1]:
# Import Pandas
import pandas as pd

In [2]:
# Imported warning modules to ignore performance warning as data is not big enough to consider efficiency of performance 
import warnings
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

Import cleaned dataset for data integration\
Imported data:
- Data 1: age25_29_ASFR_by_regional.csv
- Data 2: age22_29_five_year_yearly_gross_income_regional.csv
- Data 3: yearly_house_price_2020_2026Q1_regional.csv

In [3]:
# Import fertility rate data (for age 25-29)
df_asfr = pd.read_csv('../data/cleaned/age25_29_ASFR_by_regional.csv')
display(df_asfr)

,region_name,region_code,year_2019,year_2020,year_2021,year_2022,year_2023,year_2024
0,North East,E12000001,92.0,89.0,90.8,86.9,84.2,81.9
1,North West,E12000002,93.8,89.8,90.1,86.6,81.3,80.4
2,Yorkshire and The Humber,E12000003,97.9,92.1,93.3,88.8,85.3,84.4
3,East Midlands,E12000004,96.2,91.9,92.7,90.0,85.7,85.1
4,West Midlands,E12000005,100.4,99.0,97.2,95.8,92.9,94.5
5,East,E12000006,93.2,88.0,90.1,86.5,83.0,80.9
6,London,E12000007,58.8,56.2,55.2,53.9,50.9,51.3
7,South East,E12000008,85.1,82.1,82.7,79.6,75.0,73.0
8,South West,E12000009,86.5,82.2,82.8,75.8,73.1,68.6
9,Wales,W92000004,91.5,87.5,89.4,86.2,80.7,76.9

In [4]:
# Import gross income data (for age 22-29)
df_gross_income_original = pd.read_csv('../data/cleaned/age22_29_five_year_yearly_gross_income_regional.csv')
display(df_gross_income_original)

,region_code,region_name,2020_median_yearly_gross,2021_median_yearly_gross,2022_median_yearly_gross,2023_median_yearly_gross,2024_median_yearly_gross
0,E12000001,North East,20930.0,22016.8,24044.8,25911.6,26764.4
1,E12000002,North West,22349.6,22724.0,24653.2,26910.0,29250.0
2,E12000003,Yorkshire and The Humber,21533.2,23145.2,24715.6,26026.0,27705.6
3,E12000004,East Midlands,21923.2,23337.6,24731.2,26176.8,28308.8
4,E12000005,West Midlands,22126.0,23665.2,24850.8,26884.0,28579.2
5,E12000006,East,22859.2,24195.6,25911.6,28095.6,28901.6
6,E12000007,London,29562.0,30492.8,31933.2,33898.8,35599.2
7,E12000008,South East,23566.4,24913.2,26182.0,28901.6,29894.8
8,E12000009,South West,21678.8,22531.6,24913.2,26286.0,28454.4
9,W92000004,Wales,21070.4,21912.8,24388.0,25771.2,27414.4
10,S92000003,Scotland,22796.8,23920.0,25656.8,28459.6,29260.4

In [5]:
# Import house price
df_house_price_original = pd.read_csv('../data/cleaned/yearly_house_price_2020_2026Q1_regional.csv')

In [6]:
# Create a copy of df_house_price as the layout of this dataframe is the final layout after the integration
# therefore dataframe build based on this dataframe 
df_house_price_copy = df_house_price_original.copy()

display(df_house_price_copy)

   region_code region_name  year  house_price
0    E12000001  North East  2020     180000.0
1    E12000001  North East  2021     192000.0
2    E12000001  North East  2022     197500.0
3    E12000001  North East  2023     200250.0
4    E12000001  North East  2024     205000.0
..         ...         ...   ...          ...
72   S92000003    Scotland  2022     230250.0
73   S92000003    Scotland  2023     229750.0
74   S92000003    Scotland  2024     232000.0
75   S92000003    Scotland  2025     239750.0
76   S92000003    Scotland  2026     240000.0

[77 rows x 4 columns]

In [24]:
# Change the column name from house_price to average_house_price
# check the column name changed as expected
# df_house_price_copy.rename(columns = {'house_price': 'average_house_price'})

# change the name in the dataframe
df_house_price_copy.rename(columns = {'house_price': 'average_house_price'}, inplace=True)
display(df_house_price_copy)

   region_code region_name  year  average_house_price
0    E12000001  North East  2020             180000.0
1    E12000001  North East  2021             192000.0
2    E12000001  North East  2022             197500.0
3    E12000001  North East  2023             200250.0
4    E12000001  North East  2024             205000.0
..         ...         ...   ...                  ...
72   S92000003    Scotland  2022             230250.0
73   S92000003    Scotland  2023             229750.0
74   S92000003    Scotland  2024             232000.0
75   S92000003    Scotland  2025             239750.0
76   S92000003    Scotland  2026             240000.0

[77 rows x 4 columns]

Data cleaning to be done prior to the integration:

Gross Income Data
- Delete 'Scotland' region data as Scotland is out of the scope of our project

House Price Data
- Delete year 2025 and 2026 rows as other dataset do not have the data for 2025 and 2026 (MCAR in imcome and fertility datasets)
- Delete 'Scotland' region data as Scotland is out of the scope of our project

In [25]:
# Delete Scotland rows in gross income data in the copied dataframe df_gross_income
df_gross_income = df_gross_income_original[(df_gross_income_original['region_name'] != 'Scotland')].copy()

display(df_gross_income)

,region_code,region_name,2020_median_yearly_gross,2021_median_yearly_gross,2022_median_yearly_gross,2023_median_yearly_gross,2024_median_yearly_gross
0,E12000001,North East,20930.0,22016.8,24044.8,25911.6,26764.4
1,E12000002,North West,22349.6,22724.0,24653.2,26910.0,29250.0
2,E12000003,Yorkshire and The Humber,21533.2,23145.2,24715.6,26026.0,27705.6
3,E12000004,East Midlands,21923.2,23337.6,24731.2,26176.8,28308.8
4,E12000005,West Midlands,22126.0,23665.2,24850.8,26884.0,28579.2
5,E12000006,East,22859.2,24195.6,25911.6,28095.6,28901.6
6,E12000007,London,29562.0,30492.8,31933.2,33898.8,35599.2
7,E12000008,South East,23566.4,24913.2,26182.0,28901.6,29894.8
8,E12000009,South West,21678.8,22531.6,24913.2,26286.0,28454.4
9,W92000004,Wales,21070.4,21912.8,24388.0,25771.2,27414.4

In [26]:
# df_all will be used to integrate the three dataframe
# Delete year 2025, 2026 and Scotland rows in house price data
df_all = df_house_price_copy[(df_house_price_copy['year'] != 2025) & 
                             (df_house_price_copy['year'] != 2026) & 
                             (df_house_price_copy['region_name'] != 'Scotland')].copy()

# crate list of 'year' to use later
# year_list = df_all[(df_all['year'] != 2025) & (df_all['year'] != 2026)]['year'].unique().tolist()
year_list = df_all['year'].unique().tolist()
print(year_list)

display(df_all)

[2020, 2021, 2022, 2023, 2024]

   region_code               region_name  year  average_house_price
0    E12000001                North East  2020             180000.0
1    E12000001                North East  2021             192000.0
2    E12000001                North East  2022             197500.0
3    E12000001                North East  2023             200250.0
4    E12000001                North East  2024             205000.0
7    E12000002                North West  2020             216750.0
8    E12000002                North West  2021             237000.0
9    E12000002                North West  2022             248000.0
10   E12000002                North West  2023             248250.0
11   E12000002                North West  2024             252750.0
14   E12000003  Yorkshire and The Humber  2020             210250.0
15   E12000003  Yorkshire and The Humber  2021             228500.0
16   E12000003  Yorkshire and The Humber  2022             237000.0
17   E12000003  Yorkshire and The Humber  2023             237000.0
18   E12000003  Yorkshire and The Humber  2024             240500.0
21   E12000004             East Midlands  2020             235750.0
22   E12000004             East Midlands  2021             258250.0
23   E12000004             East Midlands  2022             271250.0
24   E12000004             East Midlands  2023             267500.0
25   E12000004             East Midlands  2024             270250.0
28   E12000005             West Midlands  2020             247000.0
29   E12000005             West Midlands  2021             266000.0
30   E12000005             West Midlands  2022             277000.0
31   E12000005             West Midlands  2023             276500.0
32   E12000005             West Midlands  2024             280000.0
35   E12000006                      East  2020             356500.0
36   E12000006                      East  2021             377750.0
37   E12000006                      East  2022             398000.0
38   E12000006                      East  2023             388000.0
39   E12000006                      East  2024             385250.0
42   E12000007                    London  2020             575250.0
43   E12000007                    London  2021             602750.0
44   E12000007                    London  2022             613500.0
45   E12000007                    London  2023             590500.0
46   E12000007                    London  2024             612000.0
49   E12000008                South East  2020             404250.0
50   E12000008                South East  2021             425500.0
51   E12000008                South East  2022             452000.0
52   E12000008                South East  2023             432000.0
53   E12000008                South East  2024             430750.0
56   E12000009                South West  2020             304000.0
57   E12000009                South West  2021             325750.0
58   E12000009                South West  2022             346750.0
59   E12000009                South West  2023             338500.0
60   E12000009                South West  2024             335500.0
63   W92000004                     Wales  2020             201000.0
64   W92000004                     Wales  2021             225000.0
65   W92000004                     Wales  2022             241250.0
66   W92000004                     Wales  2023             235750.0
67   W92000004                     Wales  2024             237250.0

In [27]:
# To make sure the data being added to df_all mapping to the rows in the set of 'region_code, 'region_name' 'year' columns,
# make the rows in those colums as row index
df_all.set_index(['region_code', 'region_name', 'year'], inplace = True)
display(df_all)

                                           average_house_price
region_code region_name              year
E12000001   North East               2020             180000.0
                                     2021             192000.0
                                     2022             197500.0
                                     2023             200250.0
                                     2024             205000.0
E12000002   North West               2020             216750.0
                                     2021             237000.0
                                     2022             248000.0
                                     2023             248250.0
                                     2024             252750.0
E12000003   Yorkshire and The Humber 2020             210250.0
                                     2021             228500.0
                                     2022             237000.0
                                     2023             237000.0
                                     2024             240500.0
E12000004   East Midlands            2020             235750.0
                                     2021             258250.0
                                     2022             271250.0
                                     2023             267500.0
                                     2024             270250.0
E12000005   West Midlands            2020             247000.0
                                     2021             266000.0
                                     2022             277000.0
                                     2023             276500.0
                                     2024             280000.0
E12000006   East                     2020             356500.0
                                     2021             377750.0
                                     2022             398000.0
                                     2023             388000.0
                                     2024             385250.0
E12000007   London                   2020             575250.0
                                     2021             602750.0
                                     2022             613500.0
                                     2023             590500.0
                                     2024             612000.0
E12000008   South East               2020             404250.0
                                     2021             425500.0
                                     2022             452000.0
                                     2023             432000.0
                                     2024             430750.0
E12000009   South West               2020             304000.0
                                     2021             325750.0
                                     2022             346750.0
                                     2023             338500.0
                                     2024             335500.0
W92000004   Wales                    2020             201000.0
                                     2021             225000.0
                                     2022             241250.0
                                     2023             235750.0
                                     2024             237250.0

In [ ]:
# test if this syntax works as expected.
# df_all.loc[('E12000001', 'North East', 2022), 'median_yearly_gross'] = 123.4
# display(df_all)
# DF displayed as expected.

Add new column of gross income data in df_all dataframe

In [28]:
# Create a list of dictionaries for income data in each row
# To create list of dictionaries, use to_dict(orient='records')
for row_income_dict in df_gross_income.to_dict(orient='records'):
    # print(row_income_dict)
    
    # for each row in the df_gross_income table
    region_code = row_income_dict['region_code']
    region_name = row_income_dict['region_name']

    for year in year_list:

        # for each year, get the row_income_dict value from the row dictionary
        gross_income_col_name = f'{year}_median_yearly_gross'
        gross_income = row_income_dict[gross_income_col_name]
        # print(gross_income)

        # push this gross_income value, into the df_all table
        df_all.loc[(region_code, region_name, year), "median_yearly_gross"] = gross_income

In [29]:
# Check
display(df_all)

                                           average_house_price  \
region_code region_name              year
E12000001   North East               2020             180000.0
                                     2021             192000.0
                                     2022             197500.0
                                     2023             200250.0
                                     2024             205000.0
E12000002   North West               2020             216750.0
                                     2021             237000.0
                                     2022             248000.0
                                     2023             248250.0
                                     2024             252750.0
E12000003   Yorkshire and The Humber 2020             210250.0
                                     2021             228500.0
                                     2022             237000.0
                                     2023             237000.0
                                     2024             240500.0
E12000004   East Midlands            2020             235750.0
                                     2021             258250.0
                                     2022             271250.0
                                     2023             267500.0
                                     2024             270250.0
E12000005   West Midlands            2020             247000.0
                                     2021             266000.0
                                     2022             277000.0
                                     2023             276500.0
                                     2024             280000.0
E12000006   East                     2020             356500.0
                                     2021             377750.0
                                     2022             398000.0
                                     2023             388000.0
                                     2024             385250.0
E12000007   London                   2020             575250.0
                                     2021             602750.0
                                     2022             613500.0
                                     2023             590500.0
                                     2024             612000.0
E12000008   South East               2020             404250.0
                                     2021             425500.0
                                     2022             452000.0
                                     2023             432000.0
                                     2024             430750.0
E12000009   South West               2020             304000.0
                                     2021             325750.0
                                     2022             346750.0
                                     2023             338500.0
                                     2024             335500.0
W92000004   Wales                    2020             201000.0
                                     2021             225000.0
                                     2022             241250.0
                                     2023             235750.0
                                     2024             237250.0

                                           median_yearly_gross
region_code region_name              year
E12000001   North East               2020              20930.0
                                     2021              22016.8
                                     2022              24044.8
                                     2023              25911.6
                                     2024              26764.4
E12000002   North West               2020              22349.6
                                     2021              22724.0
                                     2022              24653.2
                                     2023              26910.0
                                     2024              29250.0
E12000003   Yorkshire and The Humber 2020              21533.2
                                     2021              23145.2
                                     2022              24715.6
                                     2023              26026.0
                                     2024              27705.6
E12000004   East Midlands            2020              21923.2
                                     2021              23337.6
                                     2022              24731.2
                                     2023              26176.8
                                     2024              28308.8
E12000005   West Midlands            2020              22126.0
                                     2021              23665.2
                                     2022              24850.8
                                     2023              26884.0
                                     2024              28579.2
E12000006   East                     2020              22859.2
                                     2021              24195.6
                                     2022              25911.6
                                     2023              28095.6
                                     2024              28901.6
E12000007   London                   2020              29562.0
                                     2021              30492.8
                                     2022              31933.2
                                     2023              33898.8
                                     2024              35599.2
E12000008   South East               2020              23566.4
                                     2021              24913.2
                                     2022              26182.0
                                     2023              28901.6
                                     2024              29894.8
E12000009   South West               2020              21678.8
                                     2021              22531.6
                                     2022              24913.2
                                     2023              26286.0
                                     2024              28454.4
W92000004   Wales                    2020              21070.4
                                     2021              21912.8
                                     2022              24388.0
                                     2023              25771.2
                                     2024              27414.4

Repeat the same for fertility rate

In [30]:
# To see the original dataframe
display(df_asfr)

,region_name,region_code,year_2019,year_2020,year_2021,year_2022,year_2023,year_2024
0,North East,E12000001,92.0,89.0,90.8,86.9,84.2,81.9
1,North West,E12000002,93.8,89.8,90.1,86.6,81.3,80.4
2,Yorkshire and The Humber,E12000003,97.9,92.1,93.3,88.8,85.3,84.4
3,East Midlands,E12000004,96.2,91.9,92.7,90.0,85.7,85.1
4,West Midlands,E12000005,100.4,99.0,97.2,95.8,92.9,94.5
5,East,E12000006,93.2,88.0,90.1,86.5,83.0,80.9
6,London,E12000007,58.8,56.2,55.2,53.9,50.9,51.3
7,South East,E12000008,85.1,82.1,82.7,79.6,75.0,73.0
8,South West,E12000009,86.5,82.2,82.8,75.8,73.1,68.6
9,Wales,W92000004,91.5,87.5,89.4,86.2,80.7,76.9

In [31]:
# Create a list of dictionaries for income data in each row
# To create list of dictionaries, use to_dict(orient='records')
for row_fertility_dict in df_asfr.to_dict(orient='records'):
    # print(row_income_dict)
    
    # for each row in the df_gross_income table
    region_code = row_fertility_dict['region_code']
    region_name = row_fertility_dict['region_name']

    for year in year_list:

        # for each year, get the row_income_dict value from the row dictionary
        fertility_col_name = f'year_{year}'
        asfr = row_fertility_dict[fertility_col_name]
        # print(gross_income)

        # push this gross_income value, into the df_all table
        df_all.loc[(region_code, region_name, year), 'fertility_rate'] = asfr

In [32]:
# Check
display(df_all)

                                           average_house_price  \
region_code region_name              year
E12000001   North East               2020             180000.0
                                     2021             192000.0
                                     2022             197500.0
                                     2023             200250.0
                                     2024             205000.0
E12000002   North West               2020             216750.0
                                     2021             237000.0
                                     2022             248000.0
                                     2023             248250.0
                                     2024             252750.0
E12000003   Yorkshire and The Humber 2020             210250.0
                                     2021             228500.0
                                     2022             237000.0
                                     2023             237000.0
                                     2024             240500.0
E12000004   East Midlands            2020             235750.0
                                     2021             258250.0
                                     2022             271250.0
                                     2023             267500.0
                                     2024             270250.0
E12000005   West Midlands            2020             247000.0
                                     2021             266000.0
                                     2022             277000.0
                                     2023             276500.0
                                     2024             280000.0
E12000006   East                     2020             356500.0
                                     2021             377750.0
                                     2022             398000.0
                                     2023             388000.0
                                     2024             385250.0
E12000007   London                   2020             575250.0
                                     2021             602750.0
                                     2022             613500.0
                                     2023             590500.0
                                     2024             612000.0
E12000008   South East               2020             404250.0
                                     2021             425500.0
                                     2022             452000.0
                                     2023             432000.0
                                     2024             430750.0
E12000009   South West               2020             304000.0
                                     2021             325750.0
                                     2022             346750.0
                                     2023             338500.0
                                     2024             335500.0
W92000004   Wales                    2020             201000.0
                                     2021             225000.0
                                     2022             241250.0
                                     2023             235750.0
                                     2024             237250.0

                                           median_yearly_gross  fertility_rate
region_code region_name              year
E12000001   North East               2020              20930.0            89.0
                                     2021              22016.8            90.8
                                     2022              24044.8            86.9
                                     2023              25911.6            84.2
                                     2024              26764.4            81.9
E12000002   North West               2020              22349.6            89.8
                                     2021              22724.0            90.1
                                     2022              24653.2            86.6
                                     2023              26910.0            81.3
                                     2024              29250.0            80.4
E12000003   Yorkshire and The Humber 2020              21533.2            92.1
                                     2021              23145.2            93.3
                                     2022              24715.6            88.8
                                     2023              26026.0            85.3
                                     2024              27705.6            84.4
E12000004   East Midlands            2020              21923.2            91.9
                                     2021              23337.6            92.7
                                     2022              24731.2            90.0
                                     2023              26176.8            85.7
                                     2024              28308.8            85.1
E12000005   West Midlands            2020              22126.0            99.0
                                     2021              23665.2            97.2
                                     2022              24850.8            95.8
                                     2023              26884.0            92.9
                                     2024              28579.2            94.5
E12000006   East                     2020              22859.2            88.0
                                     2021              24195.6            90.1
                                     2022              25911.6            86.5
                                     2023              28095.6            83.0
                                     2024              28901.6            80.9
E12000007   London                   2020              29562.0            56.2
                                     2021              30492.8            55.2
                                     2022              31933.2            53.9
                                     2023              33898.8            50.9
                                     2024              35599.2            51.3
E12000008   South East               2020              23566.4            82.1
                                     2021              24913.2            82.7
                                     2022              26182.0            79.6
                                     2023              28901.6            75.0
                                     2024              29894.8            73.0
E12000009   South West               2020              21678.8            82.2
                                     2021              22531.6            82.8
                                     2022              24913.2            75.8
                                     2023              26286.0            73.1
                                     2024              28454.4            68.6
W92000004   Wales                    2020              21070.4            87.5
                                     2021              21912.8            89.4
                                     2022              24388.0            86.2
                                     2023              25771.2            80.7
                                     2024              27414.4            76.9

In [40]:
print('Integrated table informaiton:\n')
print(f'\n{df_all.info()}')
print(f'\nMissing values: {df_all.isnull().sum().sum()}')
print(f'\nStatistic summary:\n{df_all.describe()}')

Integrated table informaiton:

<class 'pandas.DataFrame'>
MultiIndex: 50 entries, ('E12000001', 'North East', np.int64(2020)) to ('W92000004', 'Wales', np.int64(2024))
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   average_house_price  50 non-null     float64
 1   median_yearly_gross  50 non-null     float64
 2   fertility_rate       50 non-null     float64
dtypes: float64(3)
memory usage: 3.7+ KB

None

Missing values: 0

Statistic summary:
       average_house_price  median_yearly_gross  fertility_rate
count            50.000000            50.000000       50.000000
mean         316300.000000         25771.824000       82.426000
std          119316.719666          3307.762708       11.646648
min          180000.000000         20930.000000       50.900000
25%          237000.000000         23193.300000       80.475000
50%          268875.000000         25342.200000       85.200000
75%          383375.000000         27998.100000       89.950000
max          613500.000000         35599.200000       99.000000

In [41]:
# export df_all dataframe to csv file
df_all.to_csv('../data/master/master_dataset.csv')